### ISSUE TITLE
Adding node_modules to files_to_deploy causes a crash

### ISSUE THREAD

**Issue by tomgco** [dwyl/aws-lambda-deploy#40]
Namely it looks like something happens recursivly until it breaks.

```sh
> something@1.0.0 deploy /home/rof/src/github.com/numo-labs/something
> node ./node_modules/dpl/dpl.js


Error: ENOENT: no such file or directory, open '/home/rof/src/github.com/numo-labs/something/.env'
env2 was required to load a config file but the file was not found. Please see: http://git.io/vG3UZ
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
| process.env.TMPDIR: /home/rof/src/github.com/numo-labs/something/node_modules/dpl/
| where dpl will temporarily store the Lambda Function zip file.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
fs.js:549
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^

Error: ENAMETOOLONG: name too long, open '/home/rof/src/github.com/numo-labs/something/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/dpl/dist/node_modules/aws-lambda-test-utils/test/mockContext.test.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.writeFileSync (fs.js:1156:15)
at /home/rof/src/github.com/numo-labs/something/node_modules/dpl/lib/copy_files.js:38:10
at Array.forEach (native)
at copy_files (/home/rof/src/github.com/numo-labs/something/node_modules/dpl/lib/copy_files.js:26:19)
at /home/rof/src/github.com/numo-labs/something/node_modules/dpl/lib/copy_files.js:46:7
at Array.forEach (native)
at copy_files (/home/rof/src/github.com/numo-labs/something/node_modules/dpl/lib/copy_files.js:26:19)
at /home/rof/src/github.com/numo-labs/something/node_modules/dpl/lib/copy_files.js:46:7

npm ERR! Linux 3.13.0-58-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v4.4.4/bin/node" "/home/rof/.nvm/versions/node/v4.4.4/bin/npm" "run" "deploy"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! something@1.0.0 deploy: `node ./node_modules/dpl/dpl.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the something@1.0.0 deploy script 'node ./node_modules/dpl/dpl.js'.
npm ERR! This is most likely a problem with the something package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/dpl/dpl.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs something
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls something
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rof/src/github.com/numo-labs/something/npm-debug.log
```

**Comment by nelsonic** [comment]
@tomgco yeah, we *expect* the required `node_modules` to be listed in `package.json` > `dependencies` object ... should we correct this so it's *possible* to copy all the `node_modules` into the `.zip` or should we *ignore* `node_modules` if people accidentally put them in the list of `files_to_deploy` ?

**Comment by nelsonic** [comment]
@tomgco thoughts on how we should *address* this issue? 💭 ❓

**Comment by nelsonic** [comment]
@tomgco is there an _advantage_ to adding `node_modules` to `files_to_deploy` ?
(_if you were trying to save on downloading the modules during deployment? the downside is that you would ship all your `devDependencies` in the zip and thus use more RAM on Lambda..._)

Please re-open if still an issue worth pursuing. 👍
