### ISSUE TITLE
Assumptions about git 

### ISSUE THREAD

**Issue by alfonsodev** [dwyl/aws-lambda-deploy#43]
Hi,  
Thanks for putting this project together, I'm trying to deploy my first lambda,  
I think there is some undocumented requirements regarding `git` . 

I started a new project, without a git repo, and of course it failed trying to get last commit hash, 
After doing a git init and an initial commit, npm run deploy still fails when uploading.
[Exactly here](https://github.com/numo-labs/aws-lambda-deploy/blob/master/lib/utils.js#L84):   

Why is this needed ?, it's making assumptions that I have a repo specified in my package.json  

Thanks.

Stack error  
```
npm install --production

zip -rq -X /var/folders/vs/_xvj7k5922d8hz0lqw9s403w0000gn/T/lambda-test.zip ./

git rev-parse HEAD
c981b0429f525a0c21df46886fd2e932e8a49f14

/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'url' of undefined
    at github_commit_url (/Users/alfonso/code/lambda-test/node_modules/dpl/lib/utils.js:88:29)
    at Object.description (/Users/alfonso/code/lambda-test/node_modules/dpl/lib/utils.js:101:13)
    at Response.<anonymous> (/Users/alfonso/code/lambda-test/node_modules/dpl/lib/upload.js:34:28)
    at Request.<anonymous> (/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/alfonso/code/lambda-test/node_modules/aws-sdk/lib/state_machine.js:26:10
````

**Comment by alfonsodev** [comment]
Adding  repository entry to my `package.json` fixed it  
```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/numo-labs/aws-lambda-deploy.git"
  },
 ```
It should me mention in the documentation that you need to have a git repo in place,  
or the script should be smarter and don't assume git things.

**Comment by nelsonic** [comment]
Hi @alfonsodev, well spotted, yes that is an *assumption*...
We are only using `dpl` with GitHub based projects and (I) *naively* assumed others would too...
we *could* make that an optional enhancement *if* the info is available in the `package.json` ....
If you have time, please send us a Pull Request!

**Comment by alfonsodev** [comment]
@nelsonic it's totally understandable, thanks again for open this work, besides the initial little problem with git, it's working great for me. I'll try to get some time to come with a PR.

**Comment by nelsonic** [comment]
Let's _assume_ that people using Node.js/NPM are also using GIT...
If anyone is using something _else_ please re-open this issue and explain how we need to adapt the module to accommodate other SCMs. thanks!
